# Generated by Django 5.2.7 on 2025-11-16 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateServiceClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_reference', models.CharField(help_text='Unique client reference number', max_length=50, unique=True)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRUST', 'Trust'), ('FOUNDATION', 'Foundation')], max_length=20)),
                ('client_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=100)),
                ('kyc_completed', models.BooleanField(default=False)),
                ('kyc_completion_date', models.DateField(blank=True, null=True)),
                ('kyc_review_date', models.DateField(blank=True, help_text='Next KYC review date (annual review)', null=True)),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Active Client'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], default='PROSPECT', max_length=20)),
                ('onboarding_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(help_text='ISO 4217 currency code (e.g., USD)', max_length=3)),
                ('to_currency', models.CharField(help_text='ISO 4217 currency code (e.g., EUR)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate (1 from_currency = rate to_currency)', max_digits=18)),
                ('date', models.DateField(help_text='Date for this exchange rate')),
                ('source', models.CharField(default='manual', help_text="Source of exchange rate (e.g., 'exchangerate-api', 'manual', 'central_bank')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'date'], name='offshore_ex_from_cu_89a30f_idx')],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='JurisdictionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('ANNUAL_RENEWAL', 'Annual Renewal Fee'), ('GOVT_FEE', 'Government Fee'), ('REGISTERED_AGENT', 'Registered Agent Fee'), ('REGISTERED_OFFICE', 'Registered Office Fee'), ('ANNUAL_RETURN', 'Annual Return Filing Fee'), ('ES_REPORT', 'Economic Substance Report Fee'), ('AMENDMENT', 'Amendment/Change Fee'), ('APOSTILLE', 'Apostille Fee'), ('CERTIFICATE', 'Certificate Fee'), ('OTHER', 'Other Fee')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment confirmation reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_fees', to='companies.company')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnualReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_year', models.IntegerField(help_text='Year for this annual return')),
                ('due_date', models.DateField(help_text='Due date for this filing')),
                ('filed_date', models.DateField(blank=True, help_text='Date when filed', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FILED', 'Filed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Registry reference number (if applicable)', max_length=100)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, help_text='Total assets at year end', max_digits=15, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=2, help_text='Total liabilities at year end', max_digits=15, null=True)),
                ('total_equity', models.DecimalField(blank=True, decimal_places=2, help_text='Total equity at year end', max_digits=15, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, help_text='Net income for the year', max_digits=15, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF of the annual return', null=True, upload_to='annual_returns/')),
                ('supporting_documents', models.JSONField(blank=True, help_text='List of supporting document paths', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_returns', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annual_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-filing_year', '-due_date'],
                'unique_together': {('company', 'filing_year')},
            },
        ),
        migrations.CreateModel(
            name='EconomicSubstanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_year', models.IntegerField(help_text='Year for this ES report')),
                ('submission_deadline', models.DateField(help_text='Deadline for submission')),
                ('submission_date', models.DateField(blank=True, help_text='Date when submitted', null=True)),
                ('business_activity', models.CharField(choices=[('BANKING', 'Banking Business'), ('INSURANCE', 'Insurance Business'), ('FUND_MANAGEMENT', 'Fund Management Business'), ('FINANCE_LEASING', 'Finance and Leasing Business'), ('HEADQUARTERS', 'Headquarters Business'), ('SHIPPING', 'Shipping Business'), ('HOLDING', 'Holding Company Business'), ('IP', 'Intellectual Property Business'), ('DISTRIBUTION', 'Distribution and Service Centre Business'), ('OTHER', 'Other Relevant Activity'), ('NONE', 'No Relevant Activity')], default='HOLDING', max_length=50)),
                ('activity_description', models.TextField(blank=True, help_text='Detailed description of business activities')),
                ('has_adequate_employees', models.BooleanField(default=False, help_text='Does the entity have adequate number of qualified employees?')),
                ('num_employees', models.IntegerField(blank=True, help_text='Number of full-time employees', null=True)),
                ('has_adequate_premises', models.BooleanField(default=False, help_text='Does the entity have adequate physical premises?')),
                ('premises_address', models.TextField(blank=True, help_text='Physical premises address')),
                ('has_adequate_expenditure', models.BooleanField(default=False, help_text='Does the entity incur adequate operating expenditure?')),
                ('annual_expenditure', models.DecimalField(blank=True, decimal_places=2, help_text='Annual operating expenditure in local operations', max_digits=15, null=True)),
                ('conducts_core_activities', models.BooleanField(default=False, help_text='Are core income-generating activities conducted in jurisdiction?')),
                ('core_activities_description', models.TextField(blank=True, help_text='Description of core activities conducted')),
                ('is_pure_equity_holding', models.BooleanField(default=False, help_text='Is this a pure equity holding company?')),
                ('meets_reduced_substance', models.BooleanField(default=False, help_text='Meets reduced substance requirements (for holding companies)')),
                ('meets_substance_requirements', models.BooleanField(default=False, help_text='Overall assessment: meets economic substance requirements')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Authority reference number', max_length=100)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF report', null=True, upload_to='economic_substance/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_substance_reports', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_es_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reporting_year'],
                'unique_together': {('company', 'reporting_year')},
            },
        ),
    ]
