# Generated by Django 5.2.7 on 2025-11-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_improvements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_company_f009e1_idx',
            old_name='documents_d_company_b82d07_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_upload__301055_idx',
            old_name='documents_d_upload__24c17c_idx',
        ),
    ]
