# Generated by Django 5.2.7 on 2025-10-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_group_account',
            field=models.BooleanField(default=False, help_text='True if this is a group account (non-transactional)'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='level',
            field=models.IntegerField(default=1, help_text='Account level in hierarchy (1-5)'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='normal_balance',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', help_text='Normal balance side for this account', max_length=10),
        ),
    ]
