# Generated by Django 5.2.7 on 2025-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_chartofaccounts_is_group_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='allow_multi_currency',
            field=models.BooleanField(default=False, help_text='If True, this account can hold transactions in multiple currencies'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='currency',
            field=models.CharField(blank=True, help_text='Specific currency for this account (if different from company default). ISO 4217 code.', max_length=3),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='tax_reporting_category',
            field=models.CharField(blank=True, help_text='Category for tax reporting (varies by jurisdiction)', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual renewal fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_renewal_date',
            field=models.DateField(blank=True, help_text='Next annual renewal date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Client reference number for corporate services providers', max_length=100),
        ),
    ]
