# Generated by Django 5.2.7 on 2025-11-16 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('offshore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='corporate_client',
            field=models.ForeignKey(blank=True, help_text='Corporate services client (if managed by a CSP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='offshore.corporateserviceclient'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='United States', help_text='Country name', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency for fees and accounting (ISO 4217 code)', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='entity_type',
            field=models.CharField(choices=[('US_LLC', 'US LLC'), ('US_C_CORP', 'US C-Corporation'), ('US_S_CORP', 'US S-Corporation'), ('US_PARTNERSHIP', 'US Partnership'), ('US_SOLE_PROP', 'US Sole Proprietorship'), ('IBC', 'International Business Company'), ('FOUNDATION', 'Foundation'), ('TRUST', 'Trust'), ('LIMITED', 'Limited Company'), ('EXEMPTED', 'Exempted Company'), ('LLC_OFFSHORE', 'Offshore LLC'), ('BR_LTDA', 'Sociedade Limitada (LTDA)'), ('BR_SA', 'Sociedade Anônima (S.A.)'), ('BR_EIRELI', 'EIRELI'), ('OTHER', 'Other')], default='US_LLC', help_text='Type of legal entity', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(blank=True, help_text='Date of incorporation/formation', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the company is currently active'),
        ),
        migrations.AddField(
            model_name='company',
            name='jurisdiction',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('BVI', 'British Virgin Islands'), ('KY', 'Cayman Islands'), ('BS', 'Bahamas'), ('SC', 'Seychelles'), ('PA', 'Panama'), ('BZ', 'Belize'), ('AG', 'Antigua and Barbuda'), ('DM', 'Dominica'), ('KN', 'Saint Kitts and Nevis'), ('VC', 'Saint Vincent and the Grenadines'), ('GB', 'United Kingdom'), ('IE', 'Ireland'), ('LU', 'Luxembourg'), ('MT', 'Malta'), ('CY', 'Cyprus'), ('BR', 'Brazil'), ('UY', 'Uruguay'), ('SG', 'Singapore'), ('HK', 'Hong Kong'), ('OTHER', 'Other')], default='US', help_text='Jurisdiction where the company is incorporated', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this company'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_agent_address',
            field=models.TextField(blank=True, help_text='Registered agent or registered office address'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_agent_name',
            field=models.CharField(blank=True, help_text='Registered agent or registered office name', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Company registration number (if different from tax_id)', max_length=50),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='irs_box_mapping',
            field=models.JSONField(blank=True, help_text='Mapping to IRS form boxes (for US entities)', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province/Region', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(help_text='Tax ID (EIN for US, CNPJ for Brazil, Company Number for offshore, etc.)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
