# Generated by Django 5.2.7 on 2025-10-18 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IRSForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('5472', 'Form 5472 - Information Return'), ('1099-NEC', 'Form 1099-NEC - Nonemployee Compensation'), ('1120', 'Form 1120 - Corporate Income Tax Return'), ('1040', 'Form 1040 - Individual Income Tax Return')], max_length=20)),
                ('tax_year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready to File'), ('FILED', 'Filed')], default='DRAFT', max_length=20)),
                ('form_data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='irs_forms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irs_forms', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tax_year', '-created_at'],
                'unique_together': {('company', 'form_type', 'tax_year')},
            },
        ),
    ]
