# Generated by Django 5.2.7 on 2025-11-16 21:03

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_chartofaccounts_allow_multi_currency_and_more'),
        ('documents', '0004_rename_documents_d_company_b82d07_idx_documents_d_company_f009e1_idx_and_more'),
        ('transactions', '0002_add_rag_and_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing_date', models.DateField(help_text='Last date of the closed period')),
                ('period_name', models.CharField(help_text="e.g., 'Q1 2025', 'FY 2024'", max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('AUDITED', 'Audited')], default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting Closings',
                'ordering': ['-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Snapshot timestamp (cannot be in the future)', validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)])),
                ('balance', models.DecimalField(decimal_places=2, help_text='Pre-calculated balance at this timestamp', max_digits=15)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this balance was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journal Entry Balances',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date'], name='transaction_company_89de9b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='transaction_date_3de80f_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journal_line_debit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journal_line_credit_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journal_line_debit_or_credit_not_both'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_amount_gte_zero'),
        ),
        migrations.AddField(
            model_name='accountingclosing',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_audited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingclosing',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingclosing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='companies.company'),
        ),
        migrations.AddField(
            model_name='journalentrybalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='companies.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalentrybalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='accountingclosing',
            index=models.Index(fields=['company', '-closing_date'], name='transaction_company_9bdb65_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingclosing',
            index=models.Index(fields=['company', 'status'], name='transaction_company_296b01_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingclosing',
            constraint=models.CheckConstraint(condition=models.Q(('closing_date__lte', datetime.date(2025, 11, 16))), name='closing_date_not_future'),
        ),
        migrations.AddIndex(
            model_name='journalentrybalance',
            index=models.Index(fields=['company', 'account', '-timestamp'], name='transaction_company_ada920_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentrybalance',
            index=models.Index(fields=['company', '-timestamp'], name='transaction_company_4ef931_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentrybalance',
            index=models.Index(fields=['timestamp'], name='transaction_timesta_13eb25_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentrybalance',
            constraint=models.UniqueConstraint(fields=('company', 'account', 'timestamp'), name='unique_balance_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='journalentrybalance',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp__lte', datetime.datetime(2025, 11, 16, 21, 3, 2, 924250, tzinfo=datetime.timezone.utc))), name='balance_timestamp_not_future'),
        ),
    ]
