# Generated by Django 5.2.7 on 2025-10-18 12:02

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('transactions', '0002_journalentry_transaction_company_89de9b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing_date', models.DateField(help_text='Last date of the closed period')),
                ('period_name', models.CharField(help_text="e.g., 'Q1 2025', 'FY 2024'", max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('AUDITED', 'Audited')], default='OPEN', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_audited', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closings_performed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closings', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Accounting Closings',
                'ordering': ['-closing_date'],
                'indexes': [models.Index(fields=['company', '-closing_date'], name='transaction_company_9bdb65_idx'), models.Index(fields=['company', 'status'], name='transaction_company_296b01_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('closing_date__lte', datetime.date(2025, 10, 18))), name='closing_date_not_future')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Snapshot timestamp (cannot be in the future)', validators=[django.core.validators.MaxValueValidator(django.utils.timezone.now)])),
                ('balance', models.DecimalField(decimal_places=2, help_text='Pre-calculated balance at this timestamp', max_digits=15)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this balance was verified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='companies.chartofaccounts')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Journal Entry Balances',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'account', '-timestamp'], name='transaction_company_ada920_idx'), models.Index(fields=['company', '-timestamp'], name='transaction_company_4ef931_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_13eb25_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'account', 'timestamp'), name='unique_balance_snapshot'), models.CheckConstraint(condition=models.Q(('timestamp__lte', datetime.datetime(2025, 10, 18, 12, 2, 44, 574475, tzinfo=datetime.timezone.utc))), name='balance_timestamp_not_future')],
            },
        ),
    ]
