# Generated by Django 5.2.7 on 2025-11-16 11:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_chartofaccounts_allow_multi_currency_and_more'),
        ('transactions', '0003_accountingclosing_journalentrybalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingclosing',
            name='closing_date_not_future',
        ),
        migrations.RemoveConstraint(
            model_name='journalentrybalance',
            name='balance_timestamp_not_future',
        ),
        migrations.AddConstraint(
            model_name='accountingclosing',
            constraint=models.CheckConstraint(condition=models.Q(('closing_date__lte', datetime.date(2025, 11, 16))), name='closing_date_not_future'),
        ),
        migrations.AddConstraint(
            model_name='journalentrybalance',
            constraint=models.CheckConstraint(condition=models.Q(('timestamp__lte', datetime.datetime(2025, 11, 16, 11, 36, 45, 190259, tzinfo=datetime.timezone.utc))), name='balance_timestamp_not_future'),
        ),
    ]
