# Generated by Django 5.2.7 on 2025-11-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_chartofaccounts_allow_multi_currency_and_more'),
        ('core', '0002_feedback_and_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackentry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Feedback entries'},
        ),
        migrations.AlterModelOptions(
            name='predictionmetrics',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Prediction metrics'},
        ),
        migrations.RemoveConstraint(
            model_name='predictionmetrics',
            name='core_unique_company_date',
        ),
        migrations.RenameIndex(
            model_name='feedbackentry',
            new_name='core_feedba_transac_dc4284_idx',
            old_name='core_feedback_transaction_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackentry',
            new_name='core_feedba_timesta_2eac2f_idx',
            old_name='core_feedback_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='predictionmetrics',
            new_name='core_predic_company_5f5d7c_idx',
            old_name='core_metrics_company_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='predictionmetrics',
            unique_together={('company', 'date')},
        ),
        migrations.AddIndex(
            model_name='predictionmetrics',
            index=models.Index(fields=['date'], name='core_predic_date_414099_idx'),
        ),
    ]
