# Generated by Django 5.2.7 on 2025-11-16 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_chartofaccounts_allow_multi_currency_and_more'),
        ('core', '0003_alter_feedbackentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_data', models.JSONField(help_text='Original transaction data')),
                ('predicted_account', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('model_used', models.CharField(default='claude-3-sonnet', max_length=50)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('actual_account', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Friendly name for this API key', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_classify', models.BooleanField(default=True)),
                ('can_audit', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='service',
            field=models.CharField(default='web', help_text='Service that generated the log', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional details about the action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company_id', 'timestamp'], name='core_auditl_company_e9d922_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['service', 'timestamp'], name='core_auditl_service_1d8174_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['company_id', 'created_at'], name='core_aipred_company_2e66e2_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['predicted_account', 'confidence'], name='core_aipred_predict_932071_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['was_correct'], name='core_aipred_was_cor_afac13_idx'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='companies.company'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key', 'is_active'], name='core_apikey_key_1c10b4_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['company', 'is_active'], name='core_apikey_company_fe36cb_idx'),
        ),
    ]
